version: '2'
services:
  app:
    container_name: backend
    image: back-end:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/energy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    links:
     - postgres

  postgres:
    image: postgres:14.4-alpine3.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=energy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - energy-volume:/var/lib/postgresql/data

volumes:
  energy-volume:
    external: true




